# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json

name: Deploy

on:
  schedule:
    - cron: "7 2 * * 1"  # every Monday at 02:07 UTC   https://crontab.guru/#7_2_*_*_1
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
      - name: install flyctl
        uses: pcrockett/rush-repo@c63c1ffb55357996ae5342f225e19423b8d35ebf  # v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          packages: flyctl
      - name: flyctl deploy
        run: |
          for _ in 1 2; do
            flyctl deploy \
              --app "${{ secrets.FLY_APP }}" \
              --config fly.template.toml \
              --remote-only \
              && break  # break from `for` loop if successful
            sleep 60  # sleep for 1 minute if failed
          done
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_DEPLOY_TOKEN }}
